name: Local Runner Smoke Test

on:
  workflow_dispatch:

jobs:
  test-on-local-pc:
    name: Run tests on local runner
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: dotnet test --verbosity normal
